import type { ColorOption, Product } from "./products";

const APPAREL = [
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "2XL" },
  { id: "3xl", label: "3XL" },
  { id: "4xl", label: "4XL" },
];
const WOMEN = APPAREL.filter((s) => s.id !== "3xl" && s.id !== "4xl");
const HAT = [{ id: "os", label: "One size" }];
const SOCK = [
  { id: "s", label: "S (UK 4–7)" },
  { id: "m", label: "M (UK 7–10)" },
  { id: "l", label: "L (UK 10–13)" },
];

const TEE = ["180–220gsm cotton", "Print-on-demand UK / US / EU / Asia", "Unisex unless noted"];
const HOOD = ["Mid-weight fleece", "Kangaroo pocket", "Print-on-demand"];
const EMB = ["Raised embroidery — not a cheap print", "Printful stitch, 2–5 day fulfil"];
const DRINK = ["Printful / Gelato drinkware", "Dishwasher-safe ceramic unless noted"];
const JEWEL = [
  "Gift box",
  "Printify / specialty jewelry partner",
  "Gold, silver, rose gold, ink, or orange ₿",
];

const ink = { id: "ink", label: "Ink", hex: "#0B0C0E" };
const navy = { id: "navy", label: "Navy", hex: "#1B2430" };
const btc = { id: "btc", label: "Bitcoin orange", hex: "#F7931A" };
const bone = { id: "bone", label: "Bone", hex: "#EDE6D9" };
const heather = { id: "heather", label: "Heather", hex: "#6B6E73" };
const charcoal = { id: "charcoal", label: "Charcoal", hex: "#3A3D42" };

const HODL_COLORS: ColorOption[] = [
  charcoal,
  navy,
  ink,
  btc,
  bone,
];

/** Drop 05 — Bitcoin lifestyle line. Colour keys match imagesByColor. */
export const drop05: Product[] = [
  {
    slug: "stay-humble-tee",
    name: "STAY HUMBLE STACK SATS",
    shortName: "Stay Humble",
    editionId: "HM-SHSS-001",
    priceGbp: 28,
    category: "tees",
    tag: "Meme",
    featured: true,
    cut: "unisex",
    colors: [heather, navy, ink],
    imagesByColor: {
      heather: "/products/stay-humble-tee.png",
      navy: "/products/stay-humble-tee-navy.png",
      ink: "/products/stay-humble-tee-ink.png",
    },
    description: "The two-part religion. Humble in the group chat. Relentless in the stack. Orange ₿.",
    details: TEE,
    image: "/products/stay-humble-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "cant-print-tee",
    name: "CAN'T PRINT THIS",
    shortName: "Can't Print",
    editionId: "HM-CPT-001",
    priceGbp: 28,
    category: "tees",
    tag: "Meme",
    featured: true,
    cut: "unisex",
    colors: [navy],
    imagesByColor: { navy: "/products/cant-print-tee.png" },
    description: "They can print theirs. We cannot print this. 21 million, orange ₿.",
    details: TEE,
    image: "/products/cant-print-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "genesis-2009-tee",
    name: "GENESIS 03 JAN 2009",
    shortName: "Genesis 2009",
    editionId: "HM-GEN09-001",
    priceGbp: 28,
    category: "tees",
    tag: "Meme",
    featured: true,
    cut: "unisex",
    colors: [ink],
    imagesByColor: { ink: "/products/genesis-2009-tee.png" },
    description: "The date the Chancellor was on the brink. Block one, worn.",
    details: TEE,
    image: "/products/genesis-2009-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "low-time-tee",
    name: "LOW TIME PREFERENCE",
    shortName: "LTP",
    editionId: "HM-LTP-001",
    priceGbp: 28,
    category: "tees",
    tag: "Meme",
    cut: "unisex",
    colors: [charcoal],
    imagesByColor: { charcoal: "/products/low-time-tee.png" },
    description: "Patience as a personality. Orange ₿. Not a trading slogan.",
    details: TEE,
    image: "/products/low-time-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "verify-longsleeve",
    name: "VERIFY Long Sleeve",
    shortName: "Verify LS",
    editionId: "HM-VFY-LS",
    priceGbp: 34,
    category: "longsleeves",
    tag: "Meme",
    cut: "unisex",
    colors: [ink],
    imagesByColor: { ink: "/products/verify-longsleeve.png" },
    description: "Don't trust. Verify. Then wear the sleeves in a cold hall.",
    details: ["Long sleeve jersey", ...TEE],
    image: "/products/verify-longsleeve.png",
    sizes: APPAREL,
  },
  {
    slug: "stack-sats-hoodie",
    name: "STACK SATS Hoodie",
    shortName: "Stack Hoodie",
    editionId: "HM-SAT-H",
    priceGbp: 58,
    category: "hoodies",
    tag: "Premium",
    kind: "hoodie",
    featured: true,
    finish: "embroidery",
    cut: "unisex",
    colors: [ink, navy],
    imagesByColor: {
      ink: "/products/stack-sats-hoodie.png",
      navy: "/products/stack-sats-hoodie-navy.png",
    },
    description: "Stitched ₿, STACK SATS. The conference layer that does not peel.",
    details: [...HOOD, ...EMB],
    image: "/products/stack-sats-hoodie.png",
    sizes: APPAREL,
  },
  {
    slug: "digital-energy-hoodie",
    name: "DIGITAL ENERGY Hoodie",
    shortName: "Digital Energy",
    editionId: "HM-DE-H",
    priceGbp: 55,
    category: "hoodies",
    tag: "Meme",
    kind: "hoodie",
    featured: true,
    cut: "unisex",
    colors: [navy],
    imagesByColor: { navy: "/products/digital-energy-hoodie.png" },
    description: "Saylor's frame, our cloth. Bitcoin as energy, not a ticker. Orange ₿.",
    details: HOOD,
    image: "/products/digital-energy-hoodie.png",
    sizes: APPAREL,
  },
  {
    slug: "21m-hoodie",
    name: "21 MILLION Hoodie",
    shortName: "21M Hoodie",
    editionId: "HM-21M-H",
    priceGbp: 55,
    category: "hoodies",
    tag: "Meme",
    kind: "hoodie",
    featured: true,
    cut: "unisex",
    colors: [charcoal],
    imagesByColor: { charcoal: "/products/21m-hoodie.png" },
    description: "The cap, the chart, the ₿. Number go up as a textile, not a broker screenshot.",
    details: HOOD,
    image: "/products/21m-hoodie.png",
    sizes: APPAREL,
  },
  {
    slug: "embroidered-b-hoodie",
    name: "Embroidered ₿ Hoodie",
    shortName: "Stitched B Hoodie",
    editionId: "HM-EMB-H",
    priceGbp: 62,
    category: "hoodies",
    tag: "Premium",
    kind: "hoodie",
    featured: true,
    finish: "embroidery",
    cut: "unisex",
    colors: [ink, navy],
    imagesByColor: {
      ink: "/products/embroidered-b-hoodie.png",
      navy: "/products/embroidered-b-hoodie-navy.png",
    },
    description: "Just the mark. Raised orange ₿. The quiet flex.",
    details: [...HOOD, ...EMB],
    image: "/products/embroidered-b-hoodie.png",
    sizes: APPAREL,
  },
  {
    slug: "hodl-crew",
    name: "HODL Crewneck",
    shortName: "HODL Crew",
    editionId: "HM-HODL-C",
    priceGbp: 52,
    category: "hoodies",
    tag: "Meme",
    kind: "crew",
    cut: "unisex",
    colors: [heather],
    imagesByColor: { heather: "/products/hodl-crew.png" },
    description: "No hood. Orange ₿. HODL. Conference layer.",
    details: ["Crew fleece", "Chest print"],
    image: "/products/hodl-crew.png",
    sizes: APPAREL,
  },
  {
    slug: "b-zip-hoodie",
    name: "₿ Zip Hoodie",
    shortName: "B Zip",
    editionId: "HM-BZIP-001",
    priceGbp: 62,
    category: "hoodies",
    tag: "Premium",
    kind: "zip",
    finish: "embroidery",
    cut: "unisex",
    colors: [ink],
    imagesByColor: { ink: "/products/b-zip-hoodie.png" },
    description: "Full zip. Stitched orange ₿. On and off between halls.",
    details: [...HOOD, "Full zip", ...EMB],
    image: "/products/b-zip-hoodie.png",
    sizes: APPAREL,
  },
  {
    slug: "embroidered-b-hat",
    name: "Embroidered ₿ Dad Hat",
    shortName: "Stitched B Hat",
    editionId: "HM-EMB-HAT",
    priceGbp: 32,
    category: "hats",
    tag: "Premium",
    featured: true,
    finish: "embroidery",
    colors: [navy, ink, btc, heather],
    imagesByColor: {
      navy: "/products/embroidered-b-hat-navy.png",
      ink: "/products/embroidered-b-hat-ink.png",
      btc: "/products/embroidered-b-hat-btc.png",
      heather: "/products/embroidered-b-hat-heather.png",
    },
    description: "Raised orange ₿. Navy, ink, orange, heather. The conference default, stitched.",
    details: ["Adjustable dad hat", ...EMB],
    image: "/products/embroidered-b-hat-navy.png",
    sizes: HAT,
  },
  {
    slug: "satoshi-hat",
    name: "SATOSHI Dad Hat",
    shortName: "Satoshi Hat",
    editionId: "HM-SAT-HAT",
    priceGbp: 28,
    category: "hats",
    tag: "Meme",
    finish: "embroidery",
    colors: [navy],
    imagesByColor: { navy: "/products/satoshi-hat.png" },
    description: "The name. The ₿. Nobody knows who — everybody knows the hat.",
    details: ["Adjustable", ...EMB],
    image: "/products/satoshi-hat.png",
    sizes: HAT,
  },
  {
    slug: "21m-hat",
    name: "21M Dad Hat",
    shortName: "21M Hat",
    editionId: "HM-21M-HAT",
    priceGbp: 28,
    category: "hats",
    tag: "Meme",
    finish: "embroidery",
    colors: [ink],
    imagesByColor: { ink: "/products/21m-hat.png" },
    description: "Gold 21M, orange ₿. The monetary policy, on a cap.",
    details: ["Adjustable", ...EMB],
    image: "/products/21m-hat.png",
    sizes: HAT,
  },
  {
    slug: "b-bucket",
    name: "₿ Bucket Hat",
    shortName: "B Bucket",
    editionId: "HM-BKT-002",
    priceGbp: 26,
    category: "hats",
    tag: "₿",
    colors: [navy],
    imagesByColor: { navy: "/products/b-bucket.png" },
    description: "Sun, floor, festival. Orange ₿. Not a tourist bucket.",
    details: ["Bucket", "Printed ₿"],
    image: "/products/b-bucket.png",
    sizes: HAT,
  },
  {
    slug: "b-beanie",
    name: "₿ Beanie",
    shortName: "B Beanie",
    editionId: "HM-BNE-002",
    priceGbp: 24,
    category: "hats",
    tag: "Premium",
    finish: "embroidery",
    colors: [ink],
    imagesByColor: { ink: "/products/b-beanie.png" },
    description: "Cuff stitch. Orange ₿. Prague, Amsterdam, Nashville winters.",
    details: ["Cuff beanie", ...EMB],
    image: "/products/b-beanie.png",
    sizes: HAT,
  },
  {
    slug: "hodl-mug",
    name: "HODL Mug",
    shortName: "HODL Mug",
    editionId: "HM-MUG-H",
    priceGbp: 16,
    category: "drinkware",
    tag: "Meme",
    featured: true,
    colors: [ink],
    imagesByColor: { ink: "/products/hodl-mug.png" },
    description: "Morning conviction. Orange ₿. I AM HODLING, in ceramic.",
    details: DRINK,
    image: "/products/hodl-mug.png",
  },
  {
    slug: "21m-mug",
    name: "21 MILLION Mug",
    shortName: "21M Mug",
    editionId: "HM-MUG-21",
    priceGbp: 16,
    category: "drinkware",
    tag: "Meme",
    colors: [bone],
    imagesByColor: { bone: "/products/21m-mug.png" },
    description: "The cap on the cup. Chart optional. Coffee mandatory.",
    details: DRINK,
    image: "/products/21m-mug.png",
  },
  {
    slug: "stack-sats-tumbler",
    name: "STACK SATS Tumbler",
    shortName: "Sats Tumbler",
    editionId: "HM-TUM-001",
    priceGbp: 28,
    category: "drinkware",
    tag: "Meme",
    colors: [ink],
    imagesByColor: { ink: "/products/stack-sats-tumbler.png" },
    description: "Steel. Orange ₿. Desk companion for the daily stack.",
    details: ["Stainless tumbler", "Insulated", "Printful drinkware"],
    image: "/products/stack-sats-tumbler.png",
  },
  {
    slug: "hard-money-pint",
    name: "HARD MONEY Pint",
    shortName: "HM Pint",
    editionId: "HM-PINT-001",
    priceGbp: 18,
    category: "drinkware",
    tag: "₿",
    colors: [bone],
    imagesByColor: { bone: "/products/hard-money-pint.png" },
    description: "Pint glass. Orange ₿. After the conference, not during.",
    details: ["Pint glass", "Not dishwasher-proof forever — hand wash if you care"],
    image: "/products/hard-money-pint.png",
  },
  {
    slug: "b-coasters",
    name: "₿ Coaster Set",
    shortName: "B Coasters",
    editionId: "HM-CST-002",
    priceGbp: 18,
    category: "drinkware",
    tag: "₿",
    description: "Four cork-backs. ₿ and 21M. The table knows.",
    details: ["Set of four", "Cork back"],
    image: "/products/b-coasters.png",
  },
  {
    slug: "b-pendant",
    name: "₿ Pendant",
    shortName: "B Pendant",
    editionId: "HM-JWL-B",
    priceGbp: 36,
    category: "jewelry",
    tag: "Premium",
    featured: true,
    description: "Orange enamel ₿ on a chain. Quiet in a meeting. Loud if they know.",
    details: JEWEL,
    image: "/products/b-pendant.png",
  },
  {
    slug: "21m-necklace",
    name: "21M Necklace",
    shortName: "21M Necklace",
    editionId: "HM-JWL-21",
    priceGbp: 34,
    category: "jewelry",
    tag: "Premium",
    description: "The number as a charm. Tiny ₿. Gift without a speech.",
    details: JEWEL,
    image: "/products/21m-necklace.png",
  },
  {
    slug: "b-bracelet",
    name: "₿ Bracelet",
    shortName: "B Bracelet",
    editionId: "HM-JWL-BR",
    priceGbp: 28,
    category: "jewelry",
    tag: "Premium",
    description: "Thin chain, tiny ₿. Daily wear, not costume.",
    details: JEWEL,
    image: "/products/b-bracelet.png",
  },
  {
    slug: "21m-poster",
    name: "21 MILLION Print",
    shortName: "21M Print",
    editionId: "HM-PST-21",
    priceGbp: 28,
    category: "posters",
    tag: "Chart",
    featured: true,
    description: "The cap and the curve. Frame not included. Hang it where the fiat calendar was.",
    details: ["Giclée on demand", "Ships rolled"],
    image: "/products/21m-poster.png",
  },
  {
    slug: "whitepaper-poster",
    name: "White Paper Print",
    shortName: "Paper Print",
    editionId: "HM-PST-WP",
    priceGbp: 28,
    category: "posters",
    tag: "₿",
    description: "Peer-to-peer electronic cash. 31 Oct 2008. The title page, as a print.",
    details: ["Giclée on demand", "Ships rolled"],
    image: "/products/whitepaper-poster.png",
  },
  {
    slug: "candles-poster",
    name: "Candlestick Print",
    shortName: "Candles Print",
    editionId: "HM-PST-CD",
    priceGbp: 28,
    category: "posters",
    tag: "Chart",
    description: "Green candles, orange ₿. You stayed for the chart. Now it stays on the wall.",
    details: ["Giclée on demand", "Ships rolled"],
    image: "/products/candles-poster.png",
  },
  {
    slug: "women-vneck",
    name: "₿ Women's V-Neck",
    shortName: "Women V-Neck",
    editionId: "HM-WVN-001",
    priceGbp: 28,
    category: "tees",
    tag: "Family",
    cut: "women",
    colors: [ink],
    imagesByColor: { ink: "/products/women-vneck.png" },
    description: "V-neck. Orange ₿. HARD MONEY. Same house, closer cut.",
    details: TEE,
    image: "/products/women-vneck.png",
    sizes: WOMEN,
  },
  {
    slug: "women-tank",
    name: "STACK SATS Tank",
    shortName: "Women Tank",
    editionId: "HM-WTK-001",
    priceGbp: 26,
    category: "tees",
    tag: "Family",
    cut: "women",
    colors: [navy],
    imagesByColor: { navy: "/products/women-tank.png" },
    description: "Tank. Orange ₿. Stack sats in the heat.",
    details: ["Women's tank", ...TEE],
    image: "/products/women-tank.png",
    sizes: WOMEN,
  },
  {
    slug: "b-socks",
    name: "₿ Socks",
    shortName: "B Socks",
    editionId: "HM-SOX-001",
    priceGbp: 14,
    category: "accessories",
    tag: "₿",
    colors: [ink],
    imagesByColor: { ink: "/products/b-socks.png" },
    description: "Repeating ₿. The only socks that belong at a meetup.",
    details: ["Crew socks", "Printful", "12 colours — the photo updates when you pick a colour"],
    image: "/products/b-socks.png",
    sizes: SOCK,
  },
  {
    slug: "meme-stickers",
    name: "Meme Sticker Pack",
    shortName: "Meme Stickers",
    editionId: "HM-STK-002",
    priceGbp: 8,
    category: "accessories",
    tag: "Meme",
    description: "₿, 21M, HODL, VERIFY. Die-cut. Laptop and flask.",
    details: ["Vinyl", "Weatherproof"],
    image: "/products/meme-stickers.png",
  },
  {
    slug: "b-pin",
    name: "₿ Enamel Pin",
    shortName: "B Pin",
    editionId: "HM-PIN-B",
    priceGbp: 12,
    category: "accessories",
    tag: "Premium",
    description: "Orange ₿ on black. Lapel, tote, denim.",
    details: ["Enamel", "Locking back"],
    image: "/products/b-pin.png",
  },
  {
    slug: "stack-sats-tote",
    name: "STACK SATS Tote",
    shortName: "Sats Tote",
    editionId: "HM-TOT-002",
    priceGbp: 22,
    category: "bags",
    tag: "Meme",
    description: "Canvas. Orange ₿. Booth bag and grocery bag.",
    details: ["12oz canvas", "Reinforced handles", "12 colours — the photo updates when you pick a colour"],
    image: "/products/stack-sats-tote.png",
  },
  {
    slug: "b-phone",
    name: "₿ Phone Case",
    shortName: "B Case",
    editionId: "HM-PHN-001",
    priceGbp: 22,
    category: "accessories",
    tag: "₿",
    description: "Orange ₿, 21 MILLION. The lock screen can wait.",
    details: ["Tough case", "Printful", "12 colours — the photo updates when you pick a colour"],
    image: "/products/b-phone.png",
  },
];

export const HODL_TEE_COLORS = HODL_COLORS;
