import type { ColorOption, Product } from "./products";

const APPAREL = [
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "2XL" },
  { id: "3xl", label: "3XL" },
  { id: "4xl", label: "4XL" },
];
const WOMEN = APPAREL.filter((s) => s.id !== "3xl" && s.id !== "4xl");
const YOUTH = [
  { id: "ys", label: "Youth S" },
  { id: "ym", label: "Youth M" },
  { id: "yl", label: "Youth L" },
];
const TODDLER = [
  { id: "2t", label: "2T" },
  { id: "3t", label: "3T" },
  { id: "4t", label: "4T" },
  { id: "5t", label: "5T" },
];
const INFANT = [
  { id: "3m", label: "0–3M" },
  { id: "6m", label: "3–6M" },
  { id: "12m", label: "6–12M" },
  { id: "18m", label: "12–18M" },
  { id: "24m", label: "18–24M" },
];
const HAT = [{ id: "os", label: "One size" }];

export const CLOTHING_COLORS: ColorOption[] = [
  { id: "ink", label: "Ink", hex: "#0B0C0E" },
  { id: "charcoal", label: "Charcoal", hex: "#3A3D42" },
  { id: "heather", label: "Heather", hex: "#8A8D91" },
  { id: "bone", label: "Bone", hex: "#EDE6D9" },
  { id: "navy", label: "Navy", hex: "#1B2430" },
  { id: "royal", label: "Royal blue", hex: "#1D4E89" },
  { id: "sky", label: "Sky", hex: "#5B8DEF" },
  { id: "forest", label: "Forest", hex: "#2D5A3D" },
  { id: "olive", label: "Olive", hex: "#6B7A3D" },
  { id: "red", label: "Crimson", hex: "#B42318" },
  { id: "burgundy", label: "Burgundy", hex: "#6B1D2A" },
  { id: "btc", label: "Bitcoin orange", hex: "#F7931A" },
];

const TEE = [
  "180–220gsm cotton",
  "Print-on-demand UK / US / EU / Asia",
  "12 garment colours — the photo updates when you pick a colour",
];
const HOOD = ["Mid-weight fleece", "Kangaroo pocket or zip as labelled", "12 garment colours"];
const HATD = ["One size", "Embroidered or printed ₿", "Colours as listed"];
const DRINK = ["Printful / Gelato drinkware", "Dishwasher-safe ceramic unless noted"];

type Mark = {
  id: string;
  name: string;
  short: string;
  desc: string;
  image: string;
  tag?: string;
  featured?: boolean;
  trending?: boolean;
};

const MARKS: Mark[] = [
  {
    id: "so-back",
    name: "WE ARE SO BACK",
    short: "So Back",
    desc: "The group-chat pendulum. Orange ₿. Not a price call — a mood.",
    image: "/products/so-back-tee.png",
    tag: "Meme",
    featured: true,
    trending: true,
  },
  {
    id: "so-over",
    name: "IT'S SO OVER",
    short: "So Over",
    desc: "Same chat, other hour. Wear both if you are honest.",
    image: "/products/so-over-tee.png",
    tag: "Meme",
    trending: true,
  },
  {
    id: "reserve",
    name: "STRATEGIC RESERVE",
    short: "Reserve",
    desc: "Nation-state energy, merch scale. ₿ on the chest. Not financial advice.",
    image: "/products/strategic-reserve-tee.png",
    tag: "Meme",
    featured: true,
  },
  {
    id: "no-laser",
    name: "NO LASER EYES",
    short: "No Lasers",
    desc: "The era ended. The stack did not. Tiny ₿, no lasers.",
    image: "/products/no-laser-tee.png",
    tag: "Meme",
  },
  {
    id: "pow-tweet",
    name: "PROOF OF WORK NOT PROOF OF TWEET",
    short: "PoW",
    desc: "Hash, not hot take. One joke. Orange ₿.",
    image: "/products/proof-tweet-tee.png",
    tag: "Meme",
    trending: true,
  },
  {
    id: "fiat-exp",
    name: "FIAT IS THE EXPERIMENT",
    short: "Fiat Experiment",
    desc: "They called Bitcoin the experiment. The shirt disagrees.",
    image: "/products/fiat-experiment-tee.png",
    tag: "Meme",
  },
  {
    id: "quantum",
    name: "QUANTUM CAN WAIT",
    short: "Quantum",
    desc: "FUD vintage 2026. The network is still here. ₿.",
    image: "/products/quantum-tee.png",
    tag: "Meme",
  },
  {
    id: "orange-pill",
    name: "ORANGE PILL",
    short: "Orange Pill",
    desc: "Not a prescription. Just the colour. ₿.",
    image: "/products/orange-pill-tee.png",
    tag: "Meme",
  },
  {
    id: "no-forecast",
    name: "NOT A FORECAST",
    short: "No Forecast",
    desc: "A shirt. A chart doodle. Not a target. Not advice.",
    image: "/products/not-forecast-tee.png",
    tag: "Chart",
  },
  {
    id: "four-year",
    name: "FOUR YEAR TIDE",
    short: "Four Year",
    desc: "Overlapping waves. No dates that age badly. ₿.",
    image: "/products/four-year-hoodie.png",
    tag: "Chart",
  },
  {
    id: "timechain",
    name: "TIMECHAIN",
    short: "Timechain",
    desc: "The original word. Linked rings, one orange ₿.",
    image: "/products/timechain-hoodie.png",
    tag: "Copy",
  },
  {
    id: "printer",
    name: "THE PRINTER IS THE JOKE",
    short: "Printer",
    desc: "They can print theirs. This line is the punchline. ₿.",
    image: "/products/printer-cap.png",
    tag: "Meme",
  },
];

function photo(id: string, kind: string) {
  return `/products/${id}-${kind}.png`;
}

function tee(m: Mark, extra: Partial<Product> = {}): Product {
  return {
    slug: `${m.id}-tee`,
    name: m.name,
    shortName: m.short,
    editionId: `SH-D7-${m.id.toUpperCase().slice(0, 6)}-T`,
    priceGbp: 28,
    category: "tees",
    tag: m.tag ?? "Meme",
    featured: m.featured,
    trending: m.trending,
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: m.desc,
    details: TEE,
    image: m.image,
    sizes: APPAREL,
    ...extra,
  };
}

export const drop07: Product[] = [
  ...MARKS.filter((m) =>
    ["so-back", "so-over", "reserve", "no-laser", "pow-tweet", "fiat-exp", "quantum", "orange-pill", "no-forecast"].includes(
      m.id,
    ),
  ).map((m) => tee(m)),

  {
    slug: "four-year-hoodie",
    name: "FOUR YEAR TIDE Hoodie",
    shortName: "Tide Hoodie",
    editionId: "SH-D7-TIDE-H",
    priceGbp: 58,
    category: "hoodies",
    tag: "Chart",
    kind: "hoodie",
    cut: "unisex",
    trending: true,
    colors: CLOTHING_COLORS,
    description: "Overlapping waves. Conference weather. ₿.",
    details: HOOD,
    image: "/products/four-year-hoodie.png",
    sizes: APPAREL,
  },
  {
    slug: "timechain-hoodie",
    name: "TIMECHAIN Hoodie",
    shortName: "Timechain Hoodie",
    editionId: "SH-D7-TCH-H",
    priceGbp: 58,
    category: "hoodies",
    tag: "Copy",
    kind: "hoodie",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "Linked rings. One orange ₿. The word before ‘blockchain’ got marketing.",
    details: HOOD,
    image: "/products/timechain-hoodie.png",
    sizes: APPAREL,
  },
  {
    slug: "b-mark-hoodie",
    name: "₿ Mark Hoodie",
    shortName: "B Hoodie",
    editionId: "SH-D7-B-H",
    priceGbp: 58,
    category: "hoodies",
    tag: "₿",
    kind: "hoodie",
    finish: "embroidery",
    cut: "unisex",
    featured: true,
    colors: CLOTHING_COLORS,
    description: "Just the mark. Heavy cloth. The gift that needs no thread of explanation.",
    details: HOOD,
    image: "/products/b-mark-hoodie.png",
    sizes: APPAREL,
  },
  {
    slug: "so-back-hoodie",
    name: "WE ARE SO BACK Hoodie",
    shortName: "So Back Hoodie",
    editionId: "SH-D7-BACK-H",
    priceGbp: 55,
    category: "hoodies",
    tag: "Meme",
    kind: "hoodie",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "Same joke, heavier cloth. Orange ₿.",
    details: HOOD,
    image: "/products/so-back-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "so-over-hoodie",
    name: "IT'S SO OVER Hoodie",
    shortName: "So Over Hoodie",
    editionId: "SH-D7-OVER-H",
    priceGbp: 55,
    category: "hoodies",
    tag: "Meme",
    kind: "hoodie",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "Pair it with So Back. Honesty in fleece.",
    details: HOOD,
    image: "/products/so-over-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "reserve-crew",
    name: "STRATEGIC RESERVE Crew",
    shortName: "Reserve Crew",
    editionId: "SH-D7-RSV-C",
    priceGbp: 52,
    category: "hoodies",
    tag: "Meme",
    kind: "crew",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "No hood. Same ₿. Boardroom-adjacent.",
    details: ["Crewneck fleece", "12 colours"],
    image: "/products/strategic-reserve-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "quantum-crew",
    name: "QUANTUM CAN WAIT Crew",
    shortName: "Quantum Crew",
    editionId: "SH-D7-QTM-C",
    priceGbp: 52,
    category: "hoodies",
    tag: "Meme",
    kind: "crew",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "FUD, but make it cotton.",
    details: ["Crewneck fleece", "12 colours"],
    image: "/products/quantum-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "pow-zip",
    name: "PROOF OF WORK Zip",
    shortName: "PoW Zip",
    editionId: "SH-D7-POW-Z",
    priceGbp: 58,
    category: "hoodies",
    tag: "Meme",
    kind: "zip",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "On and off between halls. The line stays.",
    details: ["Zip hoodie", "12 colours"],
    image: "/products/proof-tweet-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "fiat-zip",
    name: "FIAT EXPERIMENT Zip",
    shortName: "Fiat Zip",
    editionId: "SH-D7-FIT-Z",
    priceGbp: 58,
    category: "hoodies",
    tag: "Meme",
    kind: "zip",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "Zip. Experiment. ₿.",
    details: ["Zip hoodie", "12 colours"],
    image: "/products/fiat-experiment-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "no-laser-pullover",
    name: "NO LASER EYES Pullover",
    shortName: "No Laser Pullover",
    editionId: "SH-D7-NLS-P",
    priceGbp: 54,
    category: "hoodies",
    tag: "Meme",
    kind: "pullover",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "No zip. No lasers. ₿.",
    details: HOOD,
    image: "/products/no-laser-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "orange-pill-pullover",
    name: "ORANGE PILL Pullover",
    shortName: "Pill Pullover",
    editionId: "SH-D7-PILL-P",
    priceGbp: 54,
    category: "hoodies",
    tag: "Meme",
    kind: "pullover",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "The colour, in fleece.",
    details: HOOD,
    image: "/products/orange-pill-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "no-forecast-hoodie",
    name: "NOT A FORECAST Hoodie",
    shortName: "Forecast Hoodie",
    editionId: "SH-D7-NF-H",
    priceGbp: 55,
    category: "hoodies",
    tag: "Chart",
    kind: "hoodie",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "Still not advice. Warmer.",
    details: HOOD,
    image: "/products/not-forecast-tee.png",
    sizes: APPAREL,
  },

  {
    slug: "printer-dad-hat",
    name: "THE PRINTER IS THE JOKE Hat",
    shortName: "Printer Hat",
    editionId: "SH-D7-PRT-HAT",
    priceGbp: 26,
    category: "hats",
    tag: "Meme",
    kind: "dad",
    finish: "embroidery",
    colors: CLOTHING_COLORS,
    description: "Low profile. Stitched joke. ₿.",
    details: HATD,
    image: "/products/printer-cap.png",
    sizes: HAT,
  },
  {
    slug: "so-back-beanie",
    name: "SO BACK Beanie",
    shortName: "So Back Beanie",
    editionId: "SH-D7-BACK-BN",
    priceGbp: 24,
    category: "hats",
    tag: "Meme",
    kind: "beanie",
    finish: "embroidery",
    trending: true,
    colors: CLOTHING_COLORS,
    description: "Cuff stitch. Winter group-chat energy.",
    details: HATD,
    image: "/products/so-back-beanie.png",
    sizes: HAT,
  },
  {
    slug: "b-snapback-red",
    name: "₿ Snapback — Crimson",
    shortName: "Red Snapback",
    editionId: "SH-D7-SNP-R",
    priceGbp: 30,
    category: "hats",
    tag: "Premium",
    kind: "snapback",
    finish: "embroidery",
    colors: CLOTHING_COLORS,
    description: "Flat brim. Orange ₿ on crimson. Not a sports team — a monetary one.",
    details: HATD,
    image: "/products/b-snapback-red.png",
    sizes: HAT,
  },
  ...(["so-over", "reserve", "quantum", "pow-tweet", "fiat-exp", "no-laser", "orange-pill"] as const).map(
    (id, i): Product => {
      const m = MARKS.find((x) => x.id === id)!;
      const kinds = ["dad", "trucker", "bucket", "flexfit", "vintage", "distressed", "beanie"] as const;
      const kind = kinds[i];
      return {
        slug: `${id}-${kind}-hat`,
        name: `${m.short} ${kind[0].toUpperCase()}${kind.slice(1)} hat`,
        shortName: `${m.short} hat`,
        editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-HT`,
        priceGbp: 26,
        category: "hats",
        tag: m.tag ?? "Meme",
        kind,
        colors: CLOTHING_COLORS,
        description: `${m.desc} Hat cut.`,
        details: HATD,
        image: m.image,
        sizes: HAT,
      };
    },
  ),

  ...(["so-back", "so-over", "reserve", "no-laser", "pow-tweet", "fiat-exp", "quantum"] as const).flatMap((id) => {
    const m = MARKS.find((x) => x.id === id)!;
    const cuts: { kind: "vneck" | "tank" | "crop"; slug: string; name: string }[] = [
      { kind: "vneck", slug: `${id}-vneck`, name: `${m.short} V-neck` },
      { kind: "tank", slug: `${id}-tank`, name: `${m.short} Tank` },
      { kind: "crop", slug: `${id}-crop`, name: `${m.short} Crop` },
    ];
    return cuts.map(
      (c): Product => ({
        slug: c.slug,
        name: c.name,
        shortName: c.name,
        editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-${c.kind[0].toUpperCase()}`,
        priceGbp: 28,
        category: "tees",
        tag: m.tag ?? "Meme",
        kind: c.kind,
        cut: "women",
        colors: CLOTHING_COLORS,
        description: `${m.desc} Women’s ${c.kind}.`,
        details: [...TEE, "Women’s cut XS–2XL"],
        image: m.image,
        sizes: WOMEN,
      }),
    );
  }),

  ...(["so-back", "reserve", "stack"] as const).flatMap((id) => {
    const rows: { cut: "youth" | "toddler" | "infant"; slug: string; name: string; image: string; sizes: { id: string; label: string }[] }[] =
      [
        {
          cut: "youth",
          slug: `${id}-youth`,
          name: id === "stack" ? "STACK SATS Youth" : `${id} Youth`,
          image: "/products/stack-youth-tee.png",
          sizes: YOUTH,
        },
        {
          cut: "toddler",
          slug: `${id}-toddler`,
          name: id === "stack" ? "₿ Toddler" : `${id} Toddler`,
          image: "/products/stack-youth-tee.png",
          sizes: TODDLER,
        },
        {
          cut: "infant",
          slug: `${id}-infant`,
          name: id === "stack" ? "Node Infant" : `${id} Infant`,
          image: "/products/infant-node-onesie.png",
          sizes: INFANT,
        },
      ];
    return rows.map(
      (r): Product => ({
        slug: r.slug,
        name: r.name.replace("so-back", "SO BACK").replace("reserve", "RESERVE"),
        shortName: r.name,
        editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-${r.cut[0].toUpperCase()}`,
        priceGbp: r.cut === "youth" ? 22 : 18,
        category: "tees",
        tag: "Family",
        cut: r.cut,
        colors: CLOTHING_COLORS,
        description:
          r.cut === "infant"
            ? "Tiny ₿. No sarcasm. Family photo piece."
            : "Same ₿ as the adult line. Sized down. Giftable.",
        details: [r.cut === "youth" ? "Youth S–L" : r.cut === "toddler" ? "2T–5T" : "0–24 months"],
        image: r.image,
        sizes: r.sizes,
        retired: id !== "stack" || r.cut === "infant",
      }),
    );
  }),
  ...(["quantum", "no-laser", "orange-pill", "fiat-exp"] as const).flatMap((id) => {
    const m = MARKS.find((x) => x.id === id)!;
    return (
      [
        { cut: "youth" as const, sizes: YOUTH, price: 22 },
        { cut: "toddler" as const, sizes: TODDLER, price: 18 },
        { cut: "infant" as const, sizes: INFANT, price: 18 },
      ] as const
    ).map(
      (r): Product => ({
        slug: `${id}-${r.cut}`,
        name: `${m.short} ${r.cut[0].toUpperCase()}${r.cut.slice(1)}`,
        shortName: `${m.short} ${r.cut}`,
        editionId: `SH-D7-${id.slice(0, 3).toUpperCase()}-${r.cut[0].toUpperCase()}`,
        priceGbp: r.price,
        category: "tees",
        tag: "Family",
        cut: r.cut,
        colors: CLOTHING_COLORS,
        description:
          r.cut === "infant" ? "Small ₿. Soft. No joke they cannot grow into." : `${m.short} for a niece, nephew, or first conference.`,
        details: [r.cut],
        image: r.cut === "infant" ? "/products/infant-node-onesie.png" : "/products/stack-youth-tee.png",
        sizes: r.sizes,
        retired: true,
      }),
    );
  }),

  {
    slug: "reserve-mug",
    name: "STRATEGIC RESERVE Mug",
    shortName: "Reserve Mug",
    editionId: "SH-D7-RSV-MG",
    priceGbp: 16,
    category: "drinkware",
    tag: "Meme",
    kind: "mug",
    description: "Morning conviction. ₿ and a quiet curve.",
    details: DRINK,
    image: "/products/reserve-mug.png",
  },
  {
    slug: "stack-tumbler-green",
    name: "STACK SATS Tumbler — Forest",
    shortName: "Forest Tumbler",
    editionId: "SH-D7-SAT-TM",
    priceGbp: 28,
    category: "drinkware",
    tag: "Meme",
    kind: "tumbler",
    description: "Steel. Desk stack. Forest green, orange ₿.",
    details: ["Stainless tumbler", "Keeps the coffee honest"],
    image: "/products/stack-tumbler-green.png",
  },
  ...(["so-back", "so-over", "pow-tweet", "fiat-exp", "quantum", "no-laser", "orange-pill", "no-forecast"] as const).map(
    (id): Product => {
      const m = MARKS.find((x) => x.id === id)!;
      return {
        slug: `${id}-mug`,
        name: `${m.short} Mug`,
        shortName: `${m.short} Mug`,
        editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-MG`,
        priceGbp: 16,
        category: "drinkware",
        tag: m.tag ?? "Meme",
        kind: "mug",
        description: `${m.short} on ceramic. Dishwasher-safe conviction.`,
        details: DRINK,
        image: photo(id, "mug"),
      };
    },
  ),
  ...(["so-back", "reserve", "timechain"] as const).map(
    (id): Product => ({
      slug: `${id}-tumbler`,
      name: `${id} Tumbler`,
      shortName: `${id} tumbler`,
      editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-TM`,
      priceGbp: 28,
      category: "drinkware",
      tag: "Meme",
      kind: "tumbler",
      description: "Steel. Same ₿. Travel stack.",
      details: ["Stainless tumbler"],
      image: photo(id, "tumbler"),
    }),
  ),
  ...(["so-back", "printer"] as const).map(
    (id): Product => ({
      slug: `${id}-pint`,
      name: `${id === "printer" ? "Printer" : "SO BACK"} Pint`,
      shortName: `${id} pint`,
      editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-PT`,
      priceGbp: 18,
      category: "drinkware",
      tag: "Meme",
      kind: "pint",
      description: "After the conference. ₿ on glass.",
      details: ["Pint glass"],
      image: photo(id, "pint"),
    }),
  ),
  ...(["so-back", "reserve"] as const).map(
    (id): Product => ({
      slug: `${id}-coasters`,
      name: `${id === "reserve" ? "Reserve" : "SO BACK"} Coasters`,
      shortName: `${id} coasters`,
      editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-CO`,
      priceGbp: 14,
      category: "drinkware",
      tag: "Meme",
      kind: "coaster",
      description: "The table knows. Four-pack. ₿.",
      details: ["Set of 4"],
      image: photo(id, "coasters"),
    }),
  ),

  {
    slug: "hard-money-tote",
    name: "HARD MONEY Tote",
    shortName: "Hard Money Tote",
    editionId: "SH-D7-HM-TO",
    priceGbp: 18,
    category: "bags",
    tag: "Copy",
    featured: true,
    description: "Canvas. Orange ₿. The conference carry.",
    details: ["Canvas tote", "Print-on-demand"],
    image: "/products/hard-money-tote.png",
  },
  ...(["so-back", "reserve", "pow-tweet", "fiat-exp"] as const).map(
    (id): Product => ({
      slug: `${id}-tote`,
      name: `${MARKS.find((m) => m.id === id)!.short} Tote`,
      shortName: `${id} tote`,
      editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-TO`,
      priceGbp: 18,
      category: "bags",
      tag: "Meme",
      description: "Same line, canvas.",
      details: ["Canvas tote"],
      image: photo(id, "tote"),
    }),
  ),

  ...(["so-back", "quantum", "no-forecast"] as const).map(
    (id): Product => ({
      slug: `${id}-longsleeve`,
      name: `${MARKS.find((m) => m.id === id)!.short} Long sleeve`,
      shortName: `${id} LS`,
      editionId: `SH-D7-${id.slice(0, 4).toUpperCase()}-LS`,
      priceGbp: 34,
      category: "longsleeves",
      tag: "Meme",
      cut: "unisex",
      colors: CLOTHING_COLORS,
      description: "Conference weather. Same ₿.",
      details: TEE,
      image: MARKS.find((m) => m.id === id)!.image,
      sizes: APPAREL,
    }),
  ),

  {
    slug: "so-back-poster",
    name: "WE ARE SO BACK Print",
    shortName: "So Back Print",
    editionId: "SH-D7-BACK-PS",
    priceGbp: 22,
    category: "posters",
    tag: "Meme",
    description: "A3. The mood, framed later.",
    details: ["A3 print", "Unframed"],
    image: "/products/so-back-tee.png",
  },
  {
    slug: "reserve-poster",
    name: "STRATEGIC RESERVE Print",
    shortName: "Reserve Print",
    editionId: "SH-D7-RSV-PS",
    priceGbp: 22,
    category: "posters",
    tag: "Meme",
    description: "A3. Quiet type. ₿.",
    details: ["A3 print", "Unframed"],
    image: "/products/strategic-reserve-tee.png",
  },
  ...MARKS.filter((m) => !["so-back", "reserve"].includes(m.id)).map(
    (m): Product => ({
      slug: `${m.id}-poster`,
      name: `${m.short} Print`,
      shortName: `${m.short} print`,
      editionId: `SH-D7-${m.id.slice(0, 4).toUpperCase()}-PS`,
      priceGbp: 22,
      category: "posters",
      tag: m.tag ?? "Meme",
      description: `A3. ${m.short}. Unframed.`,
      details: ["A3 print", "Unframed"],
      image: m.image,
    }),
  ),
  ...MARKS.map(
    (m): Product => ({
      slug: `${m.id}-longsleeve`,
      name: `${m.short} Long sleeve`,
      shortName: `${m.short} LS`,
      editionId: `SH-D7-${m.id.slice(0, 4).toUpperCase()}-LS2`,
      priceGbp: 34,
      category: "longsleeves",
      tag: m.tag ?? "Meme",
      cut: "unisex",
      colors: CLOTHING_COLORS,
      description: `${m.desc} Long sleeve.`,
      details: TEE,
      image: m.image,
      sizes: APPAREL,
    }),
  ).filter((p) => !["so-back-longsleeve", "quantum-longsleeve", "no-forecast-longsleeve"].includes(p.slug)),
  ...MARKS.map(
    (m): Product => ({
      slug: `${m.id}-tote`,
      name: `${m.short} Tote`,
      shortName: `${m.short} tote`,
      editionId: `SH-D7-${m.id.slice(0, 4).toUpperCase()}-TO2`,
      priceGbp: 18,
      category: "bags",
      tag: m.tag ?? "Meme",
      description: `${m.short} on canvas.`,
      details: ["Canvas tote"],
      image: "/products/hard-money-tote.png",
      retired: true,
    }),
  ).filter((p) => !["so-back-tote", "reserve-tote", "pow-tweet-tote", "fiat-exp-tote"].includes(p.slug)),
  ...MARKS.map(
    (m): Product => ({
      slug: `${m.id}-sticker`,
      name: `${m.short} Sticker`,
      shortName: `${m.short} sticker`,
      editionId: `SH-D7-${m.id.slice(0, 4).toUpperCase()}-ST`,
      priceGbp: 6,
      category: "accessories",
      tag: m.tag ?? "Meme",
      description: `Die-cut ${m.short}. Laptop armour.`,
      details: ["Vinyl", "Weatherproof"],
      image: m.image,
      retired: true,
    }),
  ),
  ...MARKS.slice(0, 8).map(
    (m): Product => ({
      slug: `${m.id}-pin`,
      name: `${m.short} Pin`,
      shortName: `${m.short} pin`,
      editionId: `SH-D7-${m.id.slice(0, 4).toUpperCase()}-PN`,
      priceGbp: 12,
      category: "accessories",
      tag: "Premium",
      description: `Enamel ${m.short}. Lapel ₿.`,
      details: ["Enamel", "Locking back"],
      image: m.image,
      retired: true,
    }),
  ),
  ...MARKS.map(
    (m): Product => ({
      slug: `${m.id}-pendant`,
      name: `${m.short} Pendant`,
      shortName: `${m.short} pendant`,
      editionId: `SH-D7-${m.id.slice(0, 4).toUpperCase()}-JW`,
      priceGbp: 36,
      category: "jewelry",
      tag: "Premium",
      description: `${m.short} as a quiet charm. Not costume.`,
      details: ["Gift box", "Specialty jewelry partner"],
      image: "/products/b-pendant.png",
      retired: true,
    }),
  ),
  ...MARKS.map(
    (m): Product => ({
      slug: `${m.id}-bracelet`,
      name: `${m.short} Bracelet`,
      shortName: `${m.short} bracelet`,
      editionId: `SH-D7-${m.id.slice(0, 4).toUpperCase()}-BR`,
      priceGbp: 28,
      category: "jewelry",
      tag: "Premium",
      description: `Thin chain. ${m.short}. Daily ₿.`,
      details: ["Gift box"],
      image: "/products/b-bracelet.png",
      retired: true,
    }),
  ),
  ...[
    { id: "verify-x", name: "VERIFY Long sleeve", image: "/products/verify-longsleeve.png" },
    { id: "hodl-x", name: "HODL Long sleeve", image: "/products/hodl-tee.png" },
    { id: "21m-x", name: "21 MILLION Long sleeve", image: "/products/21-million-tee.png" },
    { id: "humble-x", name: "STAY HUMBLE Long sleeve", image: "/products/stay-humble-tee.png" },
    { id: "node-x", name: "RUN YOUR NODE Long sleeve", image: "/products/run-node-tee.png" },
    { id: "keys-x", name: "NOT YOUR KEYS Long sleeve", image: "/products/keys-tee.png" },
    { id: "dip-x", name: "DIP FEATURE Long sleeve", image: "/products/dip-feature-tee.png" },
  ].map(
    (m): Product => ({
      slug: `${m.id}-longsleeve`,
      name: m.name,
      shortName: m.name,
      editionId: `SH-D7-${m.id.slice(0, 6).toUpperCase()}-LS`,
      priceGbp: 34,
      category: "longsleeves",
      tag: "Meme",
      cut: "unisex",
      colors: CLOTHING_COLORS,
      description: "Conference weather. Same ₿.",
      details: TEE,
      image: m.image,
      sizes: APPAREL,
    }),
  ),
  ...[
    { id: "hodl-ps", name: "HODL Print", image: "/products/hodl-tee.png" },
    { id: "humble-ps", name: "STAY HUMBLE Print", image: "/products/stay-humble-tee.png" },
    { id: "21m-ps", name: "21 MILLION Print — drop 07", image: "/products/21-million-tee.png" },
    { id: "keys-ps", name: "NOT YOUR KEYS Print", image: "/products/keys-tee.png" },
    { id: "dip-ps", name: "DIP FEATURE Print", image: "/products/dip-feature-tee.png" },
  ].map(
    (m): Product => ({
      slug: m.id,
      name: m.name,
      shortName: m.name,
      editionId: `SH-D7-${m.id.slice(0, 6).toUpperCase()}`,
      priceGbp: 22,
      category: "posters",
      tag: "Meme",
      description: "A3. Unframed. ₿.",
      details: ["A3 print", "Unframed"],
      image: m.image,
    }),
  ),
  ...MARKS.map(
    (m): Product => ({
      slug: `${m.id}-pack`,
      name: `${m.short} Pack`,
      shortName: `${m.short} pack`,
      editionId: `SH-D7-${m.id.slice(0, 4).toUpperCase()}-PK`,
      priceGbp: 42,
      category: "bags",
      tag: m.tag ?? "Meme",
      description: `Canvas pack. ${m.short}.`,
      details: ["Canvas backpack"],
      image: "/products/hard-money-tote.png",
      retired: true,
    }),
  ),
];
