import type { ColorOption, Product } from "./products";

const MEN = [
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "2XL" },
];
const WOMEN = [
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
];
const YOUTH = [
  { id: "ys", label: "Youth S" },
  { id: "ym", label: "Youth M" },
  { id: "yl", label: "Youth L" },
];
const TODDLER = [
  { id: "2t", label: "2T" },
  { id: "3t", label: "3T" },
  { id: "4t", label: "4T" },
  { id: "5t", label: "5T" },
];
const CAP = [
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
];

const SWIM_COLORS: ColorOption[] = [
  { id: "navy", label: "Navy", hex: "#1B2430" },
  { id: "ink", label: "Ink", hex: "#0B0C0E" },
  { id: "btc", label: "Bitcoin orange", hex: "#F7931A" },
  { id: "bone", label: "Bone", hex: "#EDE6D9" },
];

const SHORT = ["Quick-dry board short", "Mesh liner", "Print-on-demand. ₿ on the leg."];
const BIKINI = ["Two-piece. Mix the set.", "Chlorine-aware print", "₿ on the band or hip."];
const ONE = ["One-piece. Full coverage option.", "Chlorine-aware print", "₿ at the chest."];
const RASH = ["UPF rash guard", "Long sleeve. Salt and pool.", "Small ₿ on the chest."];
const CAPD = ["Silicone swim cap", "One joke. Tight ₿.", "Rinse after the pool."];
const KID = ["Soft lining. Family pool.", "Small ₿. No sarcasm they cannot grow into."];

export const drop08Swim: Product[] = [
  {
    slug: "hodl-swim-shorts",
    name: "I AM HODLING Swim Shorts",
    shortName: "HODL Shorts",
    editionId: "SH-SW-HODL-MS",
    priceGbp: 32,
    category: "swimwear",
    tag: "Meme",
    kind: "shorts",
    cut: "unisex",
    featured: true,
    trending: true,
    colors: SWIM_COLORS,
    description: "The typo, poolside. Orange ₿ on the leg. Not a price call.",
    details: SHORT,
    image: "/products/hodl-swim-shorts.png",
    sizes: MEN,
  },
  {
    slug: "stack-sats-swim-shorts",
    name: "STACK SATS Swim Shorts",
    shortName: "Stack Shorts",
    editionId: "SH-SW-SAT-MS",
    priceGbp: 32,
    category: "swimwear",
    tag: "Meme",
    kind: "shorts",
    cut: "unisex",
    colors: SWIM_COLORS,
    description: "Small units. Salt water. Orange ₿.",
    details: SHORT,
    image: "/products/stack-sats-swim-shorts.png",
    sizes: MEN,
  },
  {
    slug: "21m-board-shorts",
    name: "21 MILLION Board Shorts",
    shortName: "21M Shorts",
    editionId: "SH-SW-21M-MS",
    priceGbp: 34,
    category: "swimwear",
    tag: "Copy",
    kind: "shorts",
    cut: "unisex",
    colors: SWIM_COLORS,
    description: "The cap, above the knee. That's the joke.",
    details: SHORT,
    image: "/products/21m-board-shorts.png",
    sizes: MEN,
  },
  {
    slug: "hard-money-swim-shorts",
    name: "HARD MONEY Swim Shorts",
    shortName: "Hard Money Shorts",
    editionId: "SH-SW-HM-MS",
    priceGbp: 32,
    category: "swimwear",
    tag: "Copy",
    kind: "shorts",
    cut: "unisex",
    colors: SWIM_COLORS,
    description: "Soft water. Hard money. ₿.",
    details: SHORT,
    image: "/products/hard-money-swim-shorts.png",
    sizes: MEN,
  },
  {
    slug: "btc-rash-guard",
    name: "₿ Rash Guard",
    shortName: "B Rash Guard",
    editionId: "SH-SW-B-RG",
    priceGbp: 36,
    category: "swimwear",
    tag: "₿",
    kind: "rash",
    cut: "unisex",
    featured: true,
    colors: SWIM_COLORS,
    description: "Just the mark. Long sleeve. The gift that needs no thread of explanation.",
    details: RASH,
    image: "/products/btc-rash-guard.png",
    sizes: MEN,
  },
  {
    slug: "hodl-bikini",
    name: "I AM HODLING Bikini",
    shortName: "HODL Bikini",
    editionId: "SH-SW-HODL-BI",
    priceGbp: 38,
    category: "swimwear",
    tag: "Meme",
    kind: "bikini",
    cut: "women",
    featured: true,
    colors: SWIM_COLORS,
    description: "Same typo. Two pieces. Orange ₿ on the band.",
    details: BIKINI,
    image: "/products/hodl-bikini.png",
    sizes: WOMEN,
  },
  {
    slug: "stack-sats-bikini",
    name: "STACK SATS Bikini",
    shortName: "Stack Bikini",
    editionId: "SH-SW-SAT-BI",
    priceGbp: 38,
    category: "swimwear",
    tag: "Meme",
    kind: "bikini",
    cut: "women",
    trending: true,
    colors: SWIM_COLORS,
    description: "Daily ritual, salt edition.",
    details: BIKINI,
    image: "/products/stack-sats-bikini.png",
    sizes: WOMEN,
  },
  {
    slug: "few-understand-bikini",
    name: "FEW UNDERSTAND Bikini",
    shortName: "Few Bikini",
    editionId: "SH-SW-FEW-BI",
    priceGbp: 38,
    category: "swimwear",
    tag: "Meme",
    kind: "bikini",
    cut: "women",
    colors: SWIM_COLORS,
    description: "The in-joke. If they ask, they are not the few.",
    details: BIKINI,
    image: "/products/few-understand-bikini.png",
    sizes: WOMEN,
  },
  {
    slug: "21m-one-piece",
    name: "21 MILLION One-piece",
    shortName: "21M One-piece",
    editionId: "SH-SW-21M-OP",
    priceGbp: 42,
    category: "swimwear",
    tag: "Copy",
    kind: "onepiece",
    cut: "women",
    featured: true,
    colors: SWIM_COLORS,
    description: "The supply cap, one piece. ₿ at the chest.",
    details: ONE,
    image: "/products/21m-one-piece.png",
    sizes: WOMEN,
  },
  {
    slug: "stay-humble-one-piece",
    name: "STAY HUMBLE One-piece",
    shortName: "Humble One-piece",
    editionId: "SH-SW-HUM-OP",
    priceGbp: 42,
    category: "swimwear",
    tag: "Copy",
    kind: "onepiece",
    cut: "women",
    colors: SWIM_COLORS,
    description: "Stay humble. Stack the lengths. Orange ₿.",
    details: ONE,
    image: "/products/stay-humble-one-piece.png",
    sizes: WOMEN,
  },
  {
    slug: "women-btc-rash-guard",
    name: "₿ Rash Guard — Women",
    shortName: "B Rash Women",
    editionId: "SH-SW-B-RGW",
    priceGbp: 36,
    category: "swimwear",
    tag: "₿",
    kind: "rash",
    cut: "women",
    colors: SWIM_COLORS,
    description: "Closer cut. Same orange B. Reef and hotel pool.",
    details: RASH,
    image: "/products/women-btc-rash-guard.png",
    sizes: WOMEN,
  },
  {
    slug: "stack-sats-youth-swim",
    name: "STACK SATS Youth Swim Shorts",
    shortName: "Stack Youth Swim",
    editionId: "SH-SW-SAT-YS",
    priceGbp: 24,
    category: "swimwear",
    tag: "Family",
    kind: "shorts",
    cut: "youth",
    colors: SWIM_COLORS,
    description: "Same ₿ as the adult line. Sized down. Giftable.",
    details: KID,
    image: "/products/stack-sats-youth-swim.png",
    sizes: YOUTH,
  },
  {
    slug: "orange-daily-youth-swim",
    name: "Orange. Daily. Youth One-piece",
    shortName: "Orange Daily Youth",
    editionId: "SH-SW-RX-Y",
    priceGbp: 26,
    category: "swimwear",
    tag: "Family",
    kind: "onepiece",
    cut: "youth",
    colors: SWIM_COLORS,
    description: "Pharmacy-label gag, pool edition. Small ₿.",
    details: KID,
    image: "/products/orange-daily-youth-swim.png",
    sizes: YOUTH,
  },
  {
    slug: "future-utxo-youth-rash",
    name: "Future UTXO Youth Rash Guard",
    shortName: "UTXO Rash",
    editionId: "SH-SW-UTXO-YR",
    priceGbp: 28,
    category: "swimwear",
    tag: "Family",
    kind: "rash",
    cut: "youth",
    colors: SWIM_COLORS,
    description: "Long sleeve for the niece who already knows the word.",
    details: [...RASH, "Youth S–L"],
    image: "/products/future-utxo-youth-rash.png",
    sizes: YOUTH,
  },
  {
    slug: "node-toddler-swim",
    name: "Node in training Swim",
    shortName: "Node Swim",
    editionId: "SH-SW-NODE-T",
    priceGbp: 22,
    category: "swimwear",
    tag: "Family",
    kind: "onepiece",
    cut: "toddler",
    colors: SWIM_COLORS,
    description: "Tiny ₿. Soft. No joke they cannot grow into.",
    details: KID,
    image: "/products/node-toddler-swim.png",
    sizes: TODDLER,
  },
  {
    slug: "hodl-swim-cap",
    name: "I AM HODLING Swim Cap",
    shortName: "HODL Cap",
    editionId: "SH-SW-HODL-CAP",
    priceGbp: 16,
    category: "swimwear",
    tag: "Meme",
    kind: "cap",
    cut: "unisex",
    colors: SWIM_COLORS,
    description: "Silicone. The typo, on the skull. Orange ₿.",
    details: CAPD,
    image: "/products/hodl-swim-cap.png",
    sizes: CAP,
  },
  {
    slug: "stack-sats-swim-cap-women",
    name: "STACK SATS Swim Cap — Women",
    shortName: "Stack Cap Women",
    editionId: "SH-SW-SAT-CAPW",
    priceGbp: 16,
    category: "swimwear",
    tag: "Meme",
    kind: "cap",
    cut: "women",
    colors: SWIM_COLORS,
    description: "Same line. Closer fit note on the listing. ₿.",
    details: CAPD,
    image: "/products/stack-sats-swim-cap-women.png",
    sizes: CAP,
  },
  {
    slug: "21m-swim-cap-youth",
    name: "21 MILLION Youth Swim Cap",
    shortName: "21M Youth Cap",
    editionId: "SH-SW-21M-CAPY",
    priceGbp: 14,
    category: "swimwear",
    tag: "Family",
    kind: "cap",
    cut: "youth",
    colors: SWIM_COLORS,
    description: "The cap. For a first gala. Small ₿.",
    details: [...CAPD, "Youth"],
    image: "/products/21m-swim-cap-youth.png",
    sizes: CAP,
  },
];
