import { CLOTHING_COLORS } from "./drop-07";
import type { Product } from "./products";

const APPAREL = [
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "2XL" },
  { id: "3xl", label: "3XL" },
  { id: "4xl", label: "4XL" },
];
const WOMEN = APPAREL.filter((s) => s.id !== "3xl" && s.id !== "4xl");
const HAT_SIZE = [{ id: "os", label: "One size" }];

const TEE = [
  "180–220gsm cotton",
  "Print-on-demand UK / US / EU / Asia",
  "12 garment colours — the photo updates when you pick a colour",
];
const HOOD = ["Mid-weight fleece", "Kangaroo pocket", "12 garment colours"];
const HATD = ["One size", "Embroidered or printed ₿", "Colours as listed"];
const MUG = ["11oz ceramic", "Dishwasher safe", "Printed on demand"];
const BAG = ["Canvas tote", "Print-on-demand", "12 colours — the photo updates when you pick a colour"];

export const drop09Parents: Product[] = [
  {
    slug: "bitcoin-daddy-tee",
    name: "BITCOIN DADDY Tee",
    shortName: "Bitcoin Daddy",
    editionId: "SH-D9-DAD-TEE",
    priceGbp: 28,
    category: "tees",
    tag: "Family",
    featured: true,
    trending: true,
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "The title. Orange ₿. Gift it for Father’s Day or a Tuesday.",
    details: TEE,
    image: "/products/bitcoin-daddy-tee.png",
    sizes: APPAREL,
  },
  {
    slug: "bitcoin-mummy-tee",
    name: "BITCOIN MUMMY Tee",
    shortName: "Bitcoin Mummy",
    editionId: "SH-D9-MUM-TEE",
    priceGbp: 28,
    category: "tees",
    tag: "Family",
    featured: true,
    trending: true,
    cut: "women",
    colors: CLOTHING_COLORS,
    description: "School run. Node at home. Orange ₿. No speech required.",
    details: [...TEE, "Women’s cut XS–2XL"],
    image: "/products/bitcoin-mummy-tee.png",
    sizes: WOMEN,
  },
  {
    slug: "bitcoin-daddy-hoodie",
    name: "BITCOIN DADDY Hoodie",
    shortName: "Daddy Hoodie",
    editionId: "SH-D9-DAD-HD",
    priceGbp: 55,
    category: "hoodies",
    tag: "Family",
    kind: "hoodie",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "Heavier cloth. Same joke. Orange ₿.",
    details: HOOD,
    image: "/products/bitcoin-daddy-hoodie.png",
    imagesByColor: { ink: "/products/bitcoin-daddy-hoodie.png" },
    sizes: APPAREL,
  },
  {
    slug: "bitcoin-mummy-hoodie",
    name: "BITCOIN MUMMY Hoodie",
    shortName: "Mummy Hoodie",
    editionId: "SH-D9-MUM-HD",
    priceGbp: 55,
    category: "hoodies",
    tag: "Family",
    kind: "hoodie",
    cut: "women",
    colors: CLOTHING_COLORS,
    description: "Closer cut. Same ₿. The school-gate layer.",
    details: [...HOOD, "Women’s cut XS–2XL"],
    image: "/products/bitcoin-mummy-hoodie.png",
    sizes: WOMEN,
  },
  {
    slug: "bitcoin-daddy-hat",
    name: "BITCOIN DADDY Dad Hat",
    shortName: "Daddy Hat",
    editionId: "SH-D9-DAD-HAT",
    priceGbp: 24,
    category: "hats",
    tag: "Family",
    featured: true,
    colors: CLOTHING_COLORS,
    description: "A dad hat that says it. Stitched ₿.",
    details: HATD,
    image: "/products/bitcoin-daddy-hat.png",
    sizes: HAT_SIZE,
  },
  {
    slug: "bitcoin-mummy-hat",
    name: "BITCOIN MUMMY Dad Hat",
    shortName: "Mummy Hat",
    editionId: "SH-D9-MUM-HAT",
    priceGbp: 24,
    category: "hats",
    tag: "Family",
    colors: CLOTHING_COLORS,
    description: "Low profile. Orange ₿. The other half of the pair.",
    details: HATD,
    image: "/products/bitcoin-mummy-hat.png",
    sizes: HAT_SIZE,
  },
  {
    slug: "bitcoin-daddy-mug",
    name: "BITCOIN DADDY Mug",
    shortName: "Daddy Mug",
    editionId: "SH-D9-DAD-MUG",
    priceGbp: 16,
    category: "drinkware",
    tag: "Family",
    kind: "mug",
    description: "Morning coffee. The title on ceramic. ₿.",
    details: MUG,
    image: "/products/bitcoin-daddy-mug.png",
  },
  {
    slug: "bitcoin-mummy-mug",
    name: "BITCOIN MUMMY Mug",
    shortName: "Mummy Mug",
    editionId: "SH-D9-MUM-MUG",
    priceGbp: 16,
    category: "drinkware",
    tag: "Family",
    kind: "mug",
    description: "The other mug on the shelf. Orange ₿.",
    details: MUG,
    image: "/products/bitcoin-mummy-mug.png",
  },
  {
    slug: "bitcoin-daddy-tote",
    name: "BITCOIN DADDY Tote",
    shortName: "Daddy Tote",
    editionId: "SH-D9-DAD-TO",
    priceGbp: 18,
    category: "bags",
    tag: "Family",
    colors: CLOTHING_COLORS,
    description: "Canvas. Groceries and a hardware wallet. ₿.",
    details: BAG,
    image: "/products/bitcoin-daddy-tote.png",
  },
  {
    slug: "bitcoin-mummy-tote",
    name: "BITCOIN MUMMY Tote",
    shortName: "Mummy Tote",
    editionId: "SH-D9-MUM-TO",
    priceGbp: 18,
    category: "bags",
    tag: "Family",
    colors: CLOTHING_COLORS,
    description: "Canvas. School books and sats. ₿.",
    details: BAG,
    image: "/products/bitcoin-mummy-tote.png",
  },
  {
    slug: "bitcoin-daddy-longsleeve",
    name: "BITCOIN DADDY Long sleeve",
    shortName: "Daddy LS",
    editionId: "SH-D9-DAD-LS",
    priceGbp: 34,
    category: "longsleeves",
    tag: "Family",
    cut: "unisex",
    colors: CLOTHING_COLORS,
    description: "Conference weather. Same title. Orange ₿.",
    details: TEE,
    image: "/products/bitcoin-daddy-longsleeve.png",
    sizes: APPAREL,
  },
  {
    slug: "bitcoin-mummy-longsleeve",
    name: "BITCOIN MUMMY Long sleeve",
    shortName: "Mummy LS",
    editionId: "SH-D9-MUM-LS",
    priceGbp: 34,
    category: "longsleeves",
    tag: "Family",
    cut: "women",
    colors: CLOTHING_COLORS,
    description: "Sleeves for the hall that runs cold. Orange ₿.",
    details: [...TEE, "Women’s cut XS–2XL"],
    image: "/products/bitcoin-mummy-longsleeve.png",
    sizes: WOMEN,
  },
];
