import type { Product } from "./products";

const HAT = [{ id: "os", label: "One size" }];
const WOMEN = [
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "2XL" },
];
const APPAREL = [
  ...WOMEN,
  { id: "3xl", label: "3XL" },
  { id: "4xl", label: "4XL" },
];
const HOOD = ["Mid-weight fleece", "Print-on-demand"];
const EMB = ["Raised embroidery", "Printful stitch"];
const ink = { id: "ink", label: "Ink", hex: "#0B0C0E" };
const navy = { id: "navy", label: "Navy", hex: "#1B2430" };

export const drop06: Product[] = [
  {
    slug: "b-snapback",
    name: "₿ Snapback",
    shortName: "B Snapback",
    editionId: "SH-SNP-001",
    priceGbp: 30,
    category: "hats",
    tag: "Premium",
    kind: "snapback",
    trending: true,
    finish: "embroidery",
    colors: [ink],
    imagesByColor: { ink: "/products/b-snapback.png" },
    description: "Flat brim. Raised orange ₿. Conference parking-lot energy.",
    details: ["Structured snapback", ...EMB],
    image: "/products/b-snapback.png",
    sizes: HAT,
  },
  {
    slug: "b-trucker",
    name: "₿ Trucker",
    shortName: "B Trucker",
    editionId: "SH-TRK-002",
    priceGbp: 28,
    category: "hats",
    tag: "₿",
    kind: "trucker",
    finish: "embroidery",
    colors: [navy],
    imagesByColor: { navy: "/products/b-trucker.png" },
    description: "Mesh back. Orange ₿. Floor hat that breathes.",
    details: ["Trucker mesh", ...EMB],
    image: "/products/b-trucker.png",
    sizes: HAT,
  },
  {
    slug: "b-distressed-hat",
    name: "₿ Distressed Dad Hat",
    shortName: "Distressed B",
    editionId: "SH-DST-001",
    priceGbp: 28,
    category: "hats",
    tag: "₿",
    kind: "distressed",
    finish: "embroidery",
    colors: [ink],
    imagesByColor: { ink: "/products/b-distressed-hat.png" },
    description: "Washed. Faded ₿. Looks like you stacked through a cycle.",
    details: ["Distressed dad hat", ...EMB],
    image: "/products/b-distressed-hat.png",
    sizes: HAT,
  },
  {
    slug: "b-flexfit",
    name: "₿ Flexfit",
    shortName: "B Flexfit",
    editionId: "SH-FLX-001",
    priceGbp: 30,
    category: "hats",
    tag: "Premium",
    kind: "flexfit",
    finish: "embroidery",
    colors: [navy],
    imagesByColor: { navy: "/products/b-flexfit.png" },
    description: "Stretch fit. Small orange ₿. No clasp, no fuss.",
    details: ["Flexfit stretch", ...EMB],
    image: "/products/b-flexfit.png",
    sizes: [
      { id: "s-m", label: "S/M" },
      { id: "l-xl", label: "L/XL" },
    ],
  },
  {
    slug: "b-vintage-hat",
    name: "₿ Vintage Hat",
    shortName: "Vintage B",
    editionId: "SH-VTG-001",
    priceGbp: 28,
    category: "hats",
    tag: "₿",
    kind: "vintage",
    colors: [{ id: "olive", label: "Olive", hex: "#5C6348" }],
    imagesByColor: { olive: "/products/b-vintage-hat.png" },
    description: "Olive wash. Orange ₿. The one that looks already lived-in.",
    details: ["Vintage wash dad hat"],
    image: "/products/b-vintage-hat.png",
    sizes: HAT,
  },
  {
    slug: "women-crop",
    name: "STACK SATS Crop",
    shortName: "Women Crop",
    editionId: "SH-CRP-001",
    priceGbp: 26,
    category: "tees",
    tag: "Family",
    kind: "crop",
    cut: "women",
    trending: true,
    colors: [ink],
    imagesByColor: { ink: "/products/women-crop.png" },
    description: "Crop. Orange ₿. Stack sats, shorter hem.",
    details: ["Women's crop", "Print-on-demand"],
    image: "/products/women-crop.png",
    sizes: WOMEN,
  },
  {
    slug: "21m-pullover",
    name: "21 MILLION Pullover",
    shortName: "21M Pullover",
    editionId: "SH-PUL-21",
    priceGbp: 52,
    category: "hoodies",
    tag: "Meme",
    kind: "pullover",
    trending: true,
    cut: "unisex",
    colors: [navy],
    imagesByColor: { navy: "/products/21m-pullover.png" },
    description: "No zip, no hood. The cap on heavy cotton. Orange ₿.",
    details: HOOD,
    image: "/products/21m-pullover.png",
    sizes: APPAREL,
  },
];
