export type ProductCategory =
  | "tees"
  | "longsleeves"
  | "hoodies"
  | "hats"
  | "home"
  | "bags"
  | "accessories";

export type Cut = "unisex" | "women" | "youth" | "toddler" | "infant";

export type SizeOption = { id: string; label: string };
export type ColorOption = { id: string; label: string; hex: string };

export type Product = {
  slug: string;
  name: string;
  shortName: string;
  editionId: string;
  priceGbp: number;
  category: ProductCategory;
  tag: string;
  description: string;
  details: string[];
  image: string;
  print?: string;
  sizes?: SizeOption[];
  colors?: ColorOption[];
  cut?: Cut;
  limited?: boolean;
  remaining?: number;
  featured?: boolean;
  event?: boolean;
  printful?: { variantId?: number; productId?: number };
  shopifyHandle?: string;
};

export const HOUSE_COLORS: ColorOption[] = [
  { id: "ink", label: "Ink", hex: "#0B0C0E" },
  { id: "bone", label: "Bone", hex: "#EDE6D9" },
  { id: "btc", label: "Bitcoin orange", hex: "#F7931A" },
  { id: "navy", label: "Navy", hex: "#1B2430" },
  { id: "heather", label: "Heather", hex: "#6B6E73" },
];

export const APPAREL_SIZES: SizeOption[] = [
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "2XL" },
  { id: "3xl", label: "3XL" },
  { id: "4xl", label: "4XL" },
];

export const WOMEN_SIZES: SizeOption[] = [
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "2XL" },
];

export const YOUTH_SIZES: SizeOption[] = [
  { id: "ys", label: "Youth S" },
  { id: "ym", label: "Youth M" },
  { id: "yl", label: "Youth L" },
];

export const TODDLER_SIZES: SizeOption[] = [
  { id: "2t", label: "2T" },
  { id: "3t", label: "3T" },
  { id: "4t", label: "4T" },
  { id: "5t", label: "5T" },
];

export const INFANT_SIZES: SizeOption[] = [
  { id: "3m", label: "0–3M" },
  { id: "6m", label: "3–6M" },
  { id: "12m", label: "6–12M" },
  { id: "18m", label: "12–18M" },
  { id: "24m", label: "18–24M" },
];

export const HAT_SIZES: SizeOption[] = [{ id: "os", label: "One size" }];

const TEE = [
  "180–220gsm cotton (mid-weight, event-ready)",
  "Printed on demand in UK / US / EU / Asia hubs",
  "Unisex cut unless noted",
];
const HOOD = ["Mid-weight fleece", "Kangaroo pocket", "Printed on demand"];
const HAT = ["Adjustable", "Embroidered or printed mark", "Ships from nearest hub"];

export const collections = [
  { slug: "tees", label: "T-Shirts", blurb: "The daily uniform." },
  { slug: "longsleeves", label: "Long sleeves", blurb: "Conference weather." },
  { slug: "hoodies", label: "Hoodies & crew", blurb: "Heavier cloth." },
  { slug: "hats", label: "Hats", blurb: "Dad hats, 5-panels, buckets." },
  { slug: "home", label: "Home", blurb: "Mugs, candle, throw, print." },
  { slug: "bags", label: "Bags", blurb: "Totes and a pack." },
  { slug: "accessories", label: "Marks", blurb: "Stickers and pins." },
  { slug: "family", label: "Family", blurb: "Women, youth, toddler, infant — same ₿." },
  { slug: "events", label: "Event capsules", blurb: "City drops." },
] as const;

export const products: Product[] = [
  {
    slug: "genesis-tee",
    name: "Genesis Tee",
    shortName: "Genesis",
    editionId: "OF-GEN-001",
    priceGbp: 32,
    category: "tees",
    tag: "House",
    featured: true,
    description: "Small ember seal at the chest, forged hash-geometry on the back. The first mark of the house.",
    details: TEE,
    image: "/products/genesis-tee.png",
    print: "/prints/print-genesis.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "block-height-tee",
    name: "Block Height Tee",
    shortName: "Block Height",
    editionId: "OF-BLK-001",
    priceGbp: 28,
    category: "tees",
    tag: "Core",
    featured: true,
    description: "Stacked bone numerals — a height, not a slogan. Wear the clock that does not stop.",
    details: TEE,
    image: "/products/block-height-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "timechain-tee",
    name: "Timechain Tee",
    shortName: "Timechain",
    editionId: "OF-TCH-001",
    priceGbp: 28,
    category: "tees",
    tag: "Core",
    description: "Linked incomplete rings across the chest. Quiet sequence. No shout.",
    details: TEE,
    image: "/products/timechain-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "fixed-supply-tee",
    name: "Fixed Supply Tee",
    shortName: "Fixed Supply",
    editionId: "OF-FIX-001",
    priceGbp: 28,
    category: "tees",
    tag: "Core",
    description: "Bone cloth, ember seal, twenty-one ticks on the back fold. The number is the design.",
    details: TEE,
    image: "/products/fixed-supply-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "mempool-tee",
    name: "Mempool Tee",
    shortName: "Mempool",
    editionId: "OF-MEM-001",
    priceGbp: 28,
    category: "tees",
    tag: "Core",
    description: "A field of waiting marks. One ember rectangle is included. The rest wait.",
    details: TEE,
    image: "/products/mempool-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "seal-tee",
    name: "Ember Seal Tee",
    shortName: "Seal",
    editionId: "OF-SEL-001",
    priceGbp: 30,
    category: "tees",
    tag: "House",
    featured: true,
    description: "Macro wax-seal on the back. Almost nothing on the chest. The house stamp, large.",
    details: TEE,
    image: "/products/seal-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "tailored-tee",
    name: "Ring Tailored Tee",
    shortName: "Tailored",
    editionId: "OF-TLR-001",
    priceGbp: 30,
    category: "tees",
    tag: "Fit",
    description: "Slightly tailored through the body. Gold incomplete ring at the chest. Same mark, closer cut.",
    details: [...TEE, "Closer shoulder than the boxy house tee"],
    image: "/products/tailored-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "hash-tank",
    name: "Hash Tank",
    shortName: "Tank",
    editionId: "OF-TNK-001",
    priceGbp: 26,
    category: "tees",
    tag: "Athletic",
    description: "Dry-hand tank. Ember seal at the hem, hash ticks on the side seam. Floor heat, not a gym slogan.",
    details: ["Athletic jersey", "Side-seam ticks", "Printed on demand"],
    image: "/products/hash-tank.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "mena-2026-tee",
    name: "MENA 2026 Capsule Tee",
    shortName: "MENA Capsule",
    editionId: "OF-MENA-2026",
    priceGbp: 36,
    category: "tees",
    tag: "Abu Dhabi",
    limited: true,
    remaining: 210,
    event: true,
    featured: true,
    description: "Latin and Arabic atelier mark. Numbered for Bitcoin MENA, Abu Dhabi.",
    details: [...TEE, "Numbered hang-tag OF-MENA-2026"],
    image: "/products/mena-tee.png",
    print: "/prints/print-mena.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "amsterdam-tee",
    name: "Amsterdam 2026 Tee",
    shortName: "Amsterdam",
    editionId: "OF-AMS-2026",
    priceGbp: 34,
    category: "tees",
    tag: "Amsterdam",
    event: true,
    description: "Canal-line geometry. Dress-rehearsal drop for Bitcoin Amsterdam, 5–6 Nov 2026.",
    details: TEE,
    image: "/products/amsterdam-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "prague-tee",
    name: "Prague 2027 Tee",
    shortName: "Prague",
    editionId: "OF-PRG-2027",
    priceGbp: 34,
    category: "tees",
    tag: "Prague",
    event: true,
    description: "Arch geometry for BTC Prague. Wear it in May 2027 — or before, as a claim.",
    details: TEE,
    image: "/products/prague-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "nashville-tee",
    name: "Nashville 2027 Tee",
    shortName: "Nashville",
    editionId: "OF-NSH-2027",
    priceGbp: 34,
    category: "tees",
    tag: "Nashville",
    event: true,
    description: "Hall-arch line for Bitcoin 2027. The US flagship floor.",
    details: TEE,
    image: "/products/nashville-tee.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "ember-longsleeve",
    name: "Ember Long Sleeve",
    shortName: "Ember LS",
    editionId: "OF-ELS-001",
    priceGbp: 34,
    category: "longsleeves",
    tag: "Core",
    featured: true,
    description: "Seal at the chest. Gold hash ticks down both sleeves. Built for halls that run cold.",
    details: ["Long sleeve jersey", "Sleeve ticks", "Printed on demand"],
    image: "/products/ember-longsleeve.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "difficulty-hoodie",
    name: "Difficulty Hoodie",
    shortName: "Difficulty",
    editionId: "OF-DIF-001",
    priceGbp: 55,
    category: "hoodies",
    tag: "House",
    featured: true,
    description: "Hash lattice across the chest. The visual of work that does not get easier.",
    details: [...HOOD, "Hash-geometry chest print"],
    image: "/products/difficulty-hoodie.png",
    print: "/prints/print-difficulty.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "ember-hoodie",
    name: "Ember Hoodie",
    shortName: "Ember Hoodie",
    editionId: "OF-EHD-001",
    priceGbp: 52,
    category: "hoodies",
    tag: "Core",
    description: "Quiet wordmark, ember seal. The hoodie you actually pack.",
    details: HOOD,
    image: "/products/ember-hoodie.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "zip-hoodie",
    name: "Lattice Zip Hoodie",
    shortName: "Zip",
    editionId: "OF-ZIP-001",
    priceGbp: 58,
    category: "hoodies",
    tag: "Core",
    description: "Zip front. Lattice lives on the back so the chest stays clean.",
    details: [...HOOD, "Full zip"],
    image: "/products/zip-hoodie.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "ring-crewneck",
    name: "Ring Crewneck",
    shortName: "Crew",
    editionId: "OF-CRW-001",
    priceGbp: 48,
    category: "hoodies",
    tag: "Core",
    description: "Gold incomplete-ring embroidery. No hood. Conference layer.",
    details: ["Crew fleece", "Chest embroidery", "Printed / stitched on demand"],
    image: "/products/ring-crewneck.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "hash-cap",
    name: "Hash Cap",
    shortName: "Hash Cap",
    editionId: "OF-HSH-001",
    priceGbp: 28,
    category: "hats",
    tag: "House",
    featured: true,
    description: "Structured 5-panel. Gold incomplete-ring. Conference light.",
    details: HAT,
    image: "/products/hash-cap.png",
    sizes: HAT_SIZES,
  },
  {
    slug: "ember-dad-hat",
    name: "Ember Dad Hat",
    shortName: "Dad Hat",
    editionId: "OF-EMB-001",
    priceGbp: 24,
    category: "hats",
    tag: "Core",
    description: "Low profile. Tiny gold seal. The hat that does not try.",
    details: HAT,
    image: "/products/ember-dad-hat.png",
    sizes: HAT_SIZES,
  },
  {
    slug: "desert-bucket",
    name: "Desert Bucket",
    shortName: "Bucket",
    editionId: "OF-BKT-001",
    priceGbp: 26,
    category: "hats",
    tag: "Core",
    description: "Reversible bucket. Gold ring one side, ember under-brim.",
    details: HAT,
    image: "/products/desert-bucket.png",
    sizes: HAT_SIZES,
  },
  {
    slug: "forge-beanie",
    name: "Forge Beanie",
    shortName: "Beanie",
    editionId: "OF-BNE-001",
    priceGbp: 22,
    category: "hats",
    tag: "Core",
    description: "Cuff seal in gold. Prague, Amsterdam, Nashville winters.",
    details: HAT,
    image: "/products/forge-beanie.png",
    sizes: HAT_SIZES,
  },
  {
    slug: "trucker-cap",
    name: "Ring Trucker",
    shortName: "Trucker",
    editionId: "OF-TRK-001",
    priceGbp: 26,
    category: "hats",
    tag: "Core",
    description: "Bone mesh, black front, gold ring. Floor hat.",
    details: HAT,
    image: "/products/trucker-cap.png",
    sizes: HAT_SIZES,
  },
  {
    slug: "foundry-mug",
    name: "Foundry Mug",
    shortName: "Foundry Mug",
    editionId: "OF-MUG-001",
    priceGbp: 16,
    category: "home",
    tag: "House",
    featured: true,
    description: "Bone ceramic, hash ring, ember near the handle.",
    details: ["11oz ceramic", "Dishwasher safe", "Nearest print hub"],
    image: "/products/foundry-mug.png",
  },
  {
    slug: "ink-mug",
    name: "Ink Mug",
    shortName: "Ink Mug",
    editionId: "OF-MUG-002",
    priceGbp: 16,
    category: "home",
    tag: "Core",
    description: "Matte black. Gold ticks. The other morning.",
    details: ["11oz ceramic", "Dishwasher safe"],
    image: "/products/ink-mug.png",
  },
  {
    slug: "foundry-candle",
    name: "Foundry Candle",
    shortName: "Candle",
    editionId: "OF-CND-001",
    priceGbp: 22,
    category: "home",
    tag: "Core",
    description: "Amber glass, bone label, ember seal. Burn it while a block lands.",
    details: ["Soy blend", "Tin and glass", "Print-on-demand partner"],
    image: "/products/foundry-candle.png",
  },
  {
    slug: "hash-throw",
    name: "Hash Throw",
    shortName: "Throw",
    editionId: "OF-THR-001",
    priceGbp: 55,
    category: "home",
    tag: "Core",
    featured: true,
    description: "Charcoal throw, woven seal in the corner. The one home piece that earns the suitcase.",
    details: ["Woven throw", "Corner seal", "Ships folded"],
    image: "/products/hash-throw.png",
  },
  {
    slug: "hash-poster",
    name: "Lattice Print",
    shortName: "Print",
    editionId: "OF-PST-001",
    priceGbp: 28,
    category: "home",
    tag: "Core",
    description: "Forged hash-geometry on bone stock. Frame not included.",
    details: ["Giclée on demand", "Ships rolled or flat by region"],
    image: "/products/hash-poster.png",
    print: "/prints/print-genesis.png",
  },
  {
    slug: "coaster-set",
    name: "Hash Coasters",
    shortName: "Coasters",
    editionId: "OF-CST-001",
    priceGbp: 18,
    category: "home",
    tag: "Core",
    description: "Four ceramic stamps. Four geometries. One table.",
    details: ["Set of four", "Cork back where the printer allows"],
    image: "/products/coaster-set.png",
  },
  {
    slug: "forge-tote",
    name: "Forge Tote",
    shortName: "Tote",
    editionId: "OF-TOT-001",
    priceGbp: 22,
    category: "bags",
    tag: "House",
    description: "Heavy canvas. Quiet wordmark. Booth bag and daily bag.",
    details: ["12oz canvas", "Reinforced handles"],
    image: "/products/forge-tote.png",
  },
  {
    slug: "forge-pack",
    name: "Forge Pack",
    shortName: "Pack",
    editionId: "OF-PCK-001",
    priceGbp: 32,
    category: "bags",
    tag: "Core",
    description: "Canvas pack, ember seal. Laptop-ish, conference-ish.",
    details: ["Canvas backpack", "Printed on demand"],
    image: "/products/forge-pack.png",
  },
  {
    slug: "sticker-pack",
    name: "Sticker Pack",
    shortName: "Stickers",
    editionId: "OF-STK-001",
    priceGbp: 8,
    category: "accessories",
    tag: "House",
    description: "Six die-cuts: seal, ring, hash, bilingual mark, desert line, OF.",
    details: ["Vinyl", "Weatherproof"],
    image: "/products/sticker-pack.png",
  },
  {
    slug: "pin-set",
    name: "Seal Pin Set",
    shortName: "Pins",
    editionId: "OF-PIN-001",
    priceGbp: 14,
    category: "accessories",
    tag: "Core",
    description: "Three enamel marks: ember seal, incomplete ring, OF monogram.",
    details: ["Enamel on card", "Locking backs"],
    image: "/products/pin-set.png",
  },
  {
    slug: "btc-b-tee",
    name: "Bitcoin B Tee",
    shortName: "Bitcoin B",
    editionId: "OF-BTC-B",
    priceGbp: 28,
    category: "tees",
    tag: "₿",
    featured: true,
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "The mark. Classic Bitcoin B in orange. The one you gift without explaining.",
    details: [...TEE, "Unisex XS–4XL", "Ink / bone / orange / navy / heather"],
    image: "/products/btc-b-tee.png",
    print: "/prints/print-btc-b.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "log-scale-tee",
    name: "Log Scale Tee",
    shortName: "Log Scale",
    editionId: "OF-LOG-001",
    priceGbp: 30,
    category: "tees",
    tag: "Chart",
    featured: true,
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "The punchline is the axis. Rising log curve, ₿ at the last print. No Bloomberg chrome.",
    details: TEE,
    image: "/products/log-scale-tee.png",
    print: "/prints/print-log-scale.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "dip-feature-tee",
    name: "The Dip Is The Feature",
    shortName: "Dip Feature",
    editionId: "OF-DIP-001",
    priceGbp: 30,
    category: "tees",
    tag: "Chart",
    featured: true,
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "V-shaped recovery. Dry. The kind of joke that only lands if you've sat through one.",
    details: TEE,
    image: "/products/dip-feature-tee.png",
    print: "/prints/print-dip-feature.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "joke-21-tee",
    name: "21 Million. That's The Joke.",
    shortName: "21M Joke",
    editionId: "OF-21J-001",
    priceGbp: 28,
    category: "tees",
    tag: "Copy",
    featured: true,
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "The supply cap, set as a one-liner. Small Bitcoin B underneath.",
    details: TEE,
    image: "/products/joke-21-tee.png",
    print: "/prints/print-21m-joke.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "keys-tee",
    name: "Not Your Keys Tee",
    shortName: "Keys",
    editionId: "OF-KEY-001",
    priceGbp: 28,
    category: "tees",
    tag: "Copy",
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "The sentence. Bone type, orange B. Gift it to the cousin still on an exchange.",
    details: TEE,
    image: "/products/keys-tee.png",
    print: "/prints/print-keys.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "orange-daily-tee",
    name: "Orange. Daily.",
    shortName: "Orange Daily",
    editionId: "OF-RX-001",
    priceGbp: 30,
    category: "tees",
    tag: "Family",
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "Pharmacy-label gag. Amber bottle, ₿, 21M units. Funny to Bitcoiners, wearable at Sunday lunch.",
    details: TEE,
    image: "/products/orange-daily-tee.png",
    print: "/prints/print-orange-daily.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "candles-hoodie",
    name: "Candlestick Hoodie",
    shortName: "Candles",
    editionId: "OF-CNDL-H",
    priceGbp: 55,
    category: "hoodies",
    tag: "Chart",
    featured: true,
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "White and orange candles as a textile. You stayed for the chart. Now you wear it.",
    details: HOOD,
    image: "/products/candles-hoodie.png",
    print: "/prints/print-candles.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "stayed-chart-tee",
    name: "I Stayed For The Chart",
    shortName: "Stayed",
    editionId: "OF-CHT-001",
    priceGbp: 30,
    category: "tees",
    tag: "Chart",
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "One rising line. One orange B. The whole personality.",
    details: TEE,
    image: "/products/log-scale-tee.png",
    print: "/prints/print-stayed-chart.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "ten-minutes-tee",
    name: "Ten Minutes Tee",
    shortName: "Ten Minutes",
    editionId: "OF-10M-001",
    priceGbp: 28,
    category: "tees",
    tag: "Copy",
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "Block interval as a clock. ₿ at the hub. For people who already know.",
    details: TEE,
    image: "/products/btc-b-tee.png",
    print: "/prints/print-ten-minutes.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "verify-tee",
    name: "Verify Tee",
    shortName: "Verify",
    editionId: "OF-VER-001",
    priceGbp: 28,
    category: "tees",
    tag: "Copy",
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "VERIFY. Don't trust, in a smaller voice. Orange ₿.",
    details: TEE,
    image: "/products/keys-tee.png",
    print: "/prints/print-verify.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "block-one-tee",
    name: "Since Block One",
    shortName: "Block One",
    editionId: "OF-B1-001",
    priceGbp: 28,
    category: "tees",
    tag: "Copy",
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "Not a year. A block. Orange B above the line.",
    details: TEE,
    image: "/products/joke-21-tee.png",
    print: "/prints/print-block-one.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "hashrate-tee",
    name: "Hashrate Mountain Tee",
    shortName: "Hashrate",
    editionId: "OF-HR-001",
    priceGbp: 30,
    category: "tees",
    tag: "Chart",
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "Hashrate as a quiet range. ₿ on the peak. Log scale in the corner.",
    details: TEE,
    image: "/products/log-scale-tee.png",
    print: "/prints/print-hashrate.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "difficulty-adjusts-tee",
    name: "Difficulty Adjusts Tee",
    shortName: "Difficulty Adjusts",
    editionId: "OF-DA-001",
    priceGbp: 30,
    category: "tees",
    tag: "Chart",
    cut: "unisex",
    colors: HOUSE_COLORS,
    description: "A staircase. The network does the work. You just wear the stairs.",
    details: TEE,
    image: "/products/dip-feature-tee.png",
    print: "/prints/print-difficulty-adjusts.png",
    sizes: APPAREL_SIZES,
  },
  {
    slug: "women-btc-tee",
    name: "Bitcoin B Tee — Women",
    shortName: "B Women",
    editionId: "OF-BTC-W",
    priceGbp: 28,
    category: "tees",
    tag: "Family",
    cut: "women",
    colors: HOUSE_COLORS,
    description: "Same orange B, closer cut. Gift without a different brand.",
    details: [...TEE, "Women's cut XS–2XL"],
    image: "/products/women-btc-tee.png",
    print: "/prints/print-btc-b.png",
    sizes: WOMEN_SIZES,
  },
  {
    slug: "youth-utxo-tee",
    name: "Future UTXO Youth Tee",
    shortName: "Youth UTXO",
    editionId: "OF-YTH-001",
    priceGbp: 22,
    category: "tees",
    tag: "Family",
    cut: "youth",
    colors: HOUSE_COLORS,
    description: "Orange B. Future UTXO. The insider joke, sized for a niece or nephew.",
    details: ["Youth S–L", "Same print hubs"],
    image: "/products/youth-utxo-tee.png",
    print: "/prints/print-youth-utxo.png",
    sizes: YOUTH_SIZES,
  },
  {
    slug: "toddler-btc-tee",
    name: "Bitcoin B Toddler Tee",
    shortName: "Toddler B",
    editionId: "OF-TOD-001",
    priceGbp: 18,
    category: "tees",
    tag: "Family",
    cut: "toddler",
    colors: HOUSE_COLORS,
    description: "Small B. 2T–5T. No sarcasm. Just the mark.",
    details: ["Toddler 2T–5T"],
    image: "/products/youth-utxo-tee.png",
    print: "/prints/print-btc-b.png",
    sizes: TODDLER_SIZES,
  },
  {
    slug: "infant-node-onesie",
    name: "Node In Training Onesie",
    shortName: "Node Onesie",
    editionId: "OF-INF-001",
    priceGbp: 18,
    category: "tees",
    tag: "Family",
    featured: true,
    cut: "infant",
    colors: [
      { id: "ink", label: "Ink", hex: "#0B0C0E" },
      { id: "bone", label: "Bone", hex: "#EDE6D9" },
    ],
    description: "Tiny ₿. Node in training. The family photo piece.",
    details: ["Infant 0–24 months", "Envelope neck"],
    image: "/products/infant-node-onesie.png",
    print: "/prints/print-infant-node.png",
    sizes: INFANT_SIZES,
  },
  {
    slug: "btc-dad-hat",
    name: "Bitcoin B Dad Hat",
    shortName: "B Hat",
    editionId: "OF-BTC-HAT",
    priceGbp: 24,
    category: "hats",
    tag: "₿",
    featured: true,
    colors: HOUSE_COLORS,
    description: "Embroidered orange B. Navy, ink, or bone. The conference default.",
    details: HAT,
    image: "/products/btc-dad-hat.png",
    print: "/prints/print-btc-b.png",
    sizes: HAT_SIZES,
  },
  {
    slug: "log-chart-mug",
    name: "Log Chart Mug",
    shortName: "Log Mug",
    editionId: "OF-MUG-LOG",
    priceGbp: 16,
    category: "home",
    tag: "Chart",
    description: "The curve wraps the cup. Morning log scale.",
    details: ["11oz ceramic", "Dishwasher safe"],
    image: "/products/log-chart-mug.png",
    print: "/prints/print-log-scale.png",
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function productsIn(slug: string) {
  if (slug === "events") return products.filter((p) => p.event);
  if (slug === "family") return products.filter((p) => p.cut && p.cut !== "unisex");
  return products.filter((p) => p.category === slug);
}

export function searchProducts(q: string) {
  const n = q.trim().toLowerCase();
  if (!n) return products;
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(n) ||
      p.tag.toLowerCase().includes(n) ||
      p.editionId.toLowerCase().includes(n) ||
      p.description.toLowerCase().includes(n) ||
      p.category.includes(n),
  );
}

export function relatedProducts(slug: string, limit = 4) {
  const p = getProduct(slug);
  if (!p) return products.slice(0, limit);
  return products.filter((x) => x.slug !== slug && (x.category === p.category || x.event === p.event)).slice(0, limit);
}

export function formatGbp(amount: number) {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
  }).format(amount);
}

export const SIZE_CHART = {
  tees: [
    { size: "XS", chest: "86–91", length: "68" },
    { size: "S", chest: "96–101", length: "70" },
    { size: "M", chest: "101–106", length: "72" },
    { size: "L", chest: "106–111", length: "74" },
    { size: "XL", chest: "111–116", length: "76" },
    { size: "2XL", chest: "116–121", length: "78" },
    { size: "3XL", chest: "121–127", length: "80" },
    { size: "4XL", chest: "127–132", length: "82" },
  ],
  hoodies: [
    { size: "XS", chest: "102–108", length: "66" },
    { size: "S", chest: "108–114", length: "68" },
    { size: "M", chest: "114–120", length: "70" },
    { size: "L", chest: "120–126", length: "72" },
    { size: "XL", chest: "126–132", length: "74" },
    { size: "2XL", chest: "132–138", length: "76" },
    { size: "3XL", chest: "138–144", length: "78" },
    { size: "4XL", chest: "144–150", length: "80" },
  ],
};
